# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-26 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('buildingsync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='2.0.0', max_length=100)),
            ],
        ),
    ]
