# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-27 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildingsync', '0002_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingSyncAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema', to='buildingsync.Schema')),
                ('use_cases', models.ManyToManyField(to='buildingsync.UseCase')),
            ],
        ),
    ]
