# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildingsync', '0008_usecase_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingsyncattribute',
            name='use_cases',
        ),
        migrations.AddField(
            model_name='buildingsyncattribute',
            name='optional_use_cases',
            field=models.ManyToManyField(related_name='optional_use_cases', to='buildingsync.UseCase'),
        ),
        migrations.AddField(
            model_name='buildingsyncattribute',
            name='required_use_cases',
            field=models.ManyToManyField(related_name='required_use_cases', to='buildingsync.UseCase'),
        ),
        migrations.AlterField(
            model_name='buildingsyncattribute',
            name='index',
            field=models.IntegerField(default=0, verbose_name='For a given schema, this is the linear index in the tree list'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
