# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingsync', '0009_auto_20170508_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingsyncattribute',
            name='ignored_use_cases',
            field=models.ManyToManyField(related_name='ignored_use_cases', to='buildingsync.UseCase'),
        ),
    ]
