# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingsync', '0010_buildingsyncattribute_ignored_use_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingsyncattribute',
            name='type',
            field=models.CharField(default='<unknown_type>', max_length=100),
        ),
    ]
