# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingsync', '0012_buildingsyncattribute_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingsyncattribute',
            name='pure_name',
            field=models.CharField(default='<name>', max_length=100),
        ),
    ]
