# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingsync', '0013_buildingsyncattribute_pure_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingsyncattribute',
            name='path',
            field=models.CharField(default='', max_length=500),
        ),
    ]
