version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "django"
      - dependency-name: "djangorestframework"
      - dependency-name: "djangorestframework-xml"
      - dependency-name: "django-bootstrap4"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
