exclude: |
  (?x)(
    ^bsyncviewer/static/css/owl.carousel.min.css|
    ^bsyncviewer/static/css/font-awesome.min.css|
    ^bsyncviewer/static/css/owl.theme.default.min.css|
    ^bsyncviewer/static/css/magnific-popup.css|
    ^bsyncviewer/static/css/responsive.css|
    ^bsyncviewer/static/css/et-line.css|
    ^bsyncviewer/static/img/better-logo.svg
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
        # Increased max file size from 2000KB to 75000KB to accommodate large files from being added (matching nginx config).
        args: ["--maxkb=5000"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-xml
      - id: debug-statements
      - id: mixed-line-ending
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys"]
        files: \.(json|template)$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        # for now ignoring html, javascript
        types_or: [yaml, markdown, css, scss]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --output-format=full]
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
