language: python
python:
  - '3.6.5'
cache: pip
addons:
  postgresql: '9.6'
services:
  - postgresql
env:
  matrix:
    - TOX_ENV=python
    - TOX_ENV=flake8
install:
  - sudo apt-get install python-enchant -y
  - pip install tox
  - pip install --upgrade pip
  - pip install tox coveralls
before_script:
  - psql -c "CREATE DATABASE bs_validator;" -U postgres
script:
  - tox -e $TOX_ENV
after_success:
  - test $TOX_ENV = "python" && coveralls
