language: python

python:
  - "2.7"

cache: pip

env:
  matrix:
    - TOX_ENV=python
    - TOX_ENV=flake8

install:
  - sudo apt-get install python-enchant -y
  - pip install tox
  - pip install --upgrade pip
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success: test $TOX_ENV = "python" && coveralls