# Docker Compose creates multiple containers on a single machine.
# run `docker-compose up` to create and run/link the containers
version: "3"
services:
  db-postgres:
    image: postgres:11.1
    environment:
      - POSTGRES_DB=buildingsync-website
      - POSTGRES_USER=buildingsync-website
      - POSTGRES_PASSWORD=super-secret-password
    volumes:
      - buildingsync_pgdata:/var/lib/postgresql/data
  web:
    build: .
    environment:
      - POSTGRES_DB=buildingsync-website
      - POSTGRES_USER=buildingsync-website
      - POSTGRES_PASSWORD=super-secret-password
      - SECRET_KEY=super-secret-key
      - DJANGO_SETTINGS_MODULE=bsyncviewer.settings.docker
      - DJANGO_DEBUG=False
      - BUILDINGSYNC_WEBSITE_ADMIN_USER=admin
      - BUILDINGSYNC_WEBSITE_ADMIN_EMAIL=admin@buildingsync.net
      - BUILDINGSYNC_WEBSITE_ADMIN_PASSWORD=super-secure-password
    depends_on:
      - db-postgres
    ports:
      - "8080:80"
    volumes:
      - buildingsync_media:/srv/buildingsync-website/bsyncviewer/media
volumes:
  buildingsync_pgdata:
    external: true
  buildingsync_media:
    external: true
