# Docker Compose creates multiple containers on a single machine.
# run `docker-compose -f docker-compose.prod.yml up --build` to create and run/link the containers

# This file can be deleted once the old selection site is migrated officially.
# The docker volumes should also be deleted and pointed back to the originals.

# Must set the following environment variables
#   POSTGRES_USER
#   POSTGRES_PASSWORD
#   BUILDINGSYNC_WEBSITE_ADMIN_USER
#   BUILDINGSYNC_WEBSITE_ADMIN_EMAIL
#   BUILDINGSYNC_WEBSITE_ADMIN_PASSWORD
#   SECRET_KEY

version: "3"
services:
  db-postgres:
    image: postgres:11.1
    environment:
      - POSTGRES_DB=buildingsync-website
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - buildingsync_pgdata:/var/lib/postgresql/data
      - $HOME/buildingsync-website-backups:/backups
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  web:
    build: .
    environment:
      - POSTGRES_DB=buildingsync-website
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SECRET_KEY
      - DJANGO_SETTINGS_MODULE=bsyncviewer.settings.docker
      - DJANGO_DEBUG=False
      - BUILDINGSYNC_WEBSITE_ADMIN_USER
      - BUILDINGSYNC_WEBSITE_ADMIN_EMAIL
      - BUILDINGSYNC_WEBSITE_ADMIN_PASSWORD
    depends_on:
      - db-postgres
    ports:
      - "8082:80"
    volumes:
      - buildingsync_media:/srv/buildingsync-website/bsyncviewer/media
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
volumes:
  buildingsync_pgdata:
    external: true
  buildingsync_media:
    external: true
