# Docker Compose creates multiple containers on a single machine.
# run `docker-compose up` to create and run/link the containers
version: '3'
services:
  db-postgres:
    image: postgres:9.6.10
    environment:
      - POSTGRES_DB=selection-tool
      - POSTGRES_USER=selection-tool
      - POSTGRES_PASSWORD=super-secret-password
    volumes:
      - selectiontool_pgdata:/var/lib/postgresql/data
  web:
    build: .
    environment:
      - POSTGRES_DB=selection-tool
      - POSTGRES_USER=selection-tool
      - POSTGRES_PASSWORD=super-secret-password
      - SECRET_KEY=super-secret-key
      - DJANGO_SETTINGS_MODULE=bsyncviewer.settings.docker
      - DJANGO_DEBUG=False
      - SELECTION_TOOL_ADMIN_USER=admin
      - SELECTION_TOOL_ADMIN_EMAIL=admin@buildingsync.net
      - SELECTION_TOOL_ADMIN_PASSWORD=super-secure-password
    depends_on:
      - db-postgres
    ports:
      - "8080:80"
    volumes:
      - selectiontool_mediadata:/srv/selection-tool/bsviewer/media
volumes:
  selectiontool_pgdata:
    external: true
  selectiontool_mediadata:
    external: true
