# Docker Compose creates multiple containers on a single machine.
# run `docker-compose -f docker-compose.prod.yml up --build` to create and run/link the containers

# This file can be deleted once the old selection site is migrated officially.
# The docker volumes should also be deleted and pointed back to the originals.

# Must set the following environment variables
#   POSTGRES_USER
#   POSTGRES_PASSWORD
#   SELECTION_TOOL_ADMIN_USER
#   SELECTION_TOOL_ADMIN_PASSWORD
#   SELECTION_TOOL_ADMIN_ORG
#   SECRET_KEY

version: '3'
services:
  db-postgres:
    image: postgres:11.1
    environment:
      - POSTGRES_DB=selection-tool
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - selectiontool_pgdata_redesign:/var/lib/postgresql/data
      - $HOME/selection-tool-backups:/backups
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  web:
    build: .
    environment:
      - POSTGRES_DB=selection-tool
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SECRET_KEY
      - DJANGO_SETTINGS_MODULE=bsyncviewer.settings.docker
      - DJANGO_DEBUG=False
      - SELECTION_TOOL_ADMIN_USER
      - SELECTION_TOOL_ADMIN_EMAIL
      - SELECTION_TOOL_ADMIN_PASSWORD
    depends_on:
      - db-postgres
    ports:
      - "8082:80"
    volumes:
      - selectiontool_mediadata_redesign:/srv/selection-tool/bsyncviewer/media
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
volumes:
  selectiontool_pgdata_redesign:
    external: true
  selectiontool_mediadata_redesign:
    external: true
