# Generated by Django 2.1 on 2018-08-29 22:28

import bsviewer.models.schema
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('type', models.CharField(default='<unknown_type>', max_length=100)),
                ('tree_level', models.IntegerField()),
                ('index', models.IntegerField(default=0, verbose_name='For a given schema, this is the linear index in the tree list')),
                ('path', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeEnumerationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsviewer.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Enumeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('index', models.IntegerField(default=0, verbose_name='Index in the schema')),
            ],
        ),
        migrations.CreateModel(
            name='EnumerationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0.3.0', max_length=100, unique=True)),
                ('version', models.CharField(default='0.3', max_length=100, unique=True)),
                ('schema_file', models.FileField(upload_to=bsviewer.models.schema.rename_schema_file)),
                ('schema_parsed', models.BooleanField(default=False)),
                ('mapping_template_file', models.FileField(upload_to='mapping/templates/')),
            ],
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Use Case Name', max_length=100)),
                ('make_public', models.BooleanField(default=False)),
                ('import_file', models.FileField(help_text='Upload a csv file containing the mapping of your use case to the BuildingSync schema.', null=True, upload_to='use_case_mappings/')),
            ],
        ),
        migrations.CreateModel(
            name='UseCaseAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Ignored'), (1, 'Optional'), (2, 'Required')], default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsviewer.Attribute')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsviewer.UseCase')),
            ],
        ),
        migrations.CreateModel(
            name='UseCaseEnumeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Ignored'), (1, 'Optional'), (2, 'Required')], default=0)),
                ('enumeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsviewer.Enumeration')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsviewer.UseCase')),
            ],
        ),
        migrations.AddField(
            model_name='usecase',
            name='attributes',
            field=models.ManyToManyField(through='bsviewer.UseCaseAttribute', to='bsviewer.Attribute'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='enumerations',
            field=models.ManyToManyField(through='bsviewer.UseCaseEnumeration', to='bsviewer.Enumeration'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usecase',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsviewer.Schema'),
        ),
        migrations.AddField(
            model_name='enumerationclass',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsviewer.Schema'),
        ),
        migrations.AddField(
            model_name='enumeration',
            name='enumeration_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enumerations', to='bsviewer.EnumerationClass'),
        ),
        migrations.AddField(
            model_name='enumeration',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsviewer.Schema'),
        ),
        migrations.AddField(
            model_name='attributeenumerationclass',
            name='enumeration_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsviewer.EnumerationClass'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='enumeration_classes',
            field=models.ManyToManyField(through='bsviewer.AttributeEnumerationClass', to='bsviewer.EnumerationClass'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='bsviewer.Schema'),
        ),
        migrations.AlterUniqueTogether(
            name='usecaseenumeration',
            unique_together={('enumeration', 'use_case')},
        ),
        migrations.AlterUniqueTogether(
            name='usecaseattribute',
            unique_together={('attribute', 'use_case')},
        ),
    ]
