# Generated by Django 2.1 on 2018-08-27 16:31

import bsviewer.models.schema
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='schema_file',
            field=models.FileField(default='schema.xsd', upload_to=bsviewer.models.schema.rename_schema_file),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schema',
            name='schema_parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(default='0.2.0', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='version',
            field=models.CharField(default='0.2', max_length=100, unique=True),
        ),
    ]
