# Generated by Django 2.1 on 2018-09-01 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enumeration',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enumerations', to='bsviewer.Schema'),
        ),
    ]
