# Generated by Django 2.1 on 2018-08-22 21:52

import bsviewer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='file',
            field=models.FileField(default='schema.xsd', upload_to=bsviewer.models.rename_schema_file),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schema',
            name='version',
            field=models.CharField(default='0.2', max_length=100, unique=True),
        ),
    ]
