# Generated by Django 2.1 on 2018-08-28 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='schema',
            field=models.ForeignKey(default=0.3, on_delete=django.db.models.deletion.CASCADE, to='bsviewer.Schema'),
            preserve_default=False,
        ),
    ]
