# Generated by Django 2.1 on 2018-08-29 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enumeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('class_name', models.CharField(max_length=250)),
                ('index', models.IntegerField(default=0, verbose_name='Index in the schema')),
                ('path', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='buildingsyncattribute',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='bsviewer.Schema'),
        ),
        migrations.AddField(
            model_name='enumeration',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enumerations', to='bsviewer.BuildingSyncAttribute'),
        ),
    ]
