# Generated by Django 2.1 on 2018-08-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsviewer', '0003_auto_20180822_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema',
            old_name='file',
            new_name='schema_file',
        ),
        migrations.AddField(
            model_name='schema',
            name='schema_parsed',
            field=models.BooleanField(default=False),
        ),
    ]
