# Generated by Django 2.1 on 2018-08-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsviewer', '0003_usecase_make_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecase',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='show',
        ),
        migrations.AddField(
            model_name='usecase',
            name='name',
            field=models.CharField(default='Use Case Name', max_length=100),
        ),
    ]
