# Generated by Django 2.1 on 2018-08-29 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsviewer', '0004_auto_20180829_0317'),
        ('bsviewer', '0002_auto_20180829_0331'),
    ]

    operations = [
    ]
