# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('std211', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard211instance',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='standard211instance',
            name='raw_file_data',
        ),
        migrations.RemoveField(
            model_name='standard211instance',
            name='spreadsheet_file',
        ),
        migrations.AddField(
            model_name='standard211instance',
            name='data_string',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
