# Generated by Django 2.1.7 on 2019-05-01 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsyncviewer', '0004_auto_20190501_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCaseAttributeEnumeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsyncviewer.Enumeration')),
                ('enumerationClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsyncviewer.EnumerationClass')),
                ('use_case_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsyncviewer.UseCaseAttribute')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usecaseenumeration',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='usecaseenumeration',
            name='enumeration',
        ),
        migrations.RemoveField(
            model_name='usecaseenumeration',
            name='use_case',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='enumerations',
        ),
        migrations.DeleteModel(
            name='UseCaseEnumeration',
        ),
        migrations.AlterUniqueTogether(
            name='usecaseattributeenumeration',
            unique_together={('enumeration', 'use_case_attribute')},
        ),
    ]
