# Generated by Django 2.1.11 on 2019-10-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsyncviewer', '0007_auto_20190507_0310'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usecaseattribute',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='usecaseattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='usecaseattribute',
            name='use_case',
        ),
        migrations.AlterUniqueTogether(
            name='usecaseattributeenumeration',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='usecaseattributeenumeration',
            name='use_case_attribute',
        ),
        migrations.RemoveField(
            model_name='usecaserequiredpairedelement',
            name='paired_attribute',
        ),
        migrations.RemoveField(
            model_name='usecaserequiredpairedelement',
            name='use_case_attribute',
        ),
        migrations.RemoveField(
            model_name='usecaseudf',
            name='associated_field',
        ),
        migrations.RemoveField(
            model_name='usecaseudf',
            name='use_case_attribute',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='usecase_template_file',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='parsing_errors',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='usecase_parsed',
        ),
        migrations.DeleteModel(
            name='UseCaseAttribute',
        ),
        migrations.DeleteModel(
            name='UseCaseAttributeEnumeration',
        ),
        migrations.DeleteModel(
            name='UseCaseRequiredPairedElement',
        ),
        migrations.DeleteModel(
            name='UseCaseUDF',
        ),
    ]
