# Generated by Django 2.1.11 on 2019-11-10 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsyncviewer', '0008_auto_20191028_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedesmapping',
            name='match_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='import_file',
            field=models.FileField(blank=True, help_text='This should be a Schematron file defining the use case', null=True, upload_to='usecase_mappings/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['sch'])]),
        ),
    ]
