# Generated by Django 2.2.13 on 2021-05-26 15:18

from django.db import migrations, models

import bsyncviewer.models.schema


class Migration(migrations.Migration):

    dependencies = [
        ('bsyncviewer', '0009_auto_20191110_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='enumerations_file',
            field=models.FileField(help_text='The enumerations JSON file built in the BuildingSync/schema repository which includes terms and measures.', null=True, upload_to=bsyncviewer.models.schema.rename_enumerations_file),
        ),
    ]
