# Generated by Django 2.2.24 on 2021-12-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsyncviewer', '0010_schema_enumerations_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedesenumeration',
            name='term',
            field=models.CharField(max_length=100),
        ),
    ]
