# Generated by Django 2.2.24 on 2022-04-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsyncviewer', '0012_auto_20211228_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedesenumeration',
            name='content_uuid',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='bedesenumeration',
            name='term',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bedesenumeration',
            name='url',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='bedesterm',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bedesterm',
            name='content_uuid',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='bedesterm',
            name='term',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bedesterm',
            name='url',
            field=models.CharField(max_length=400),
        ),
    ]
