# Generated by Django 2.2.28 on 2025-01-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bsyncviewer", "0013_auto_20220408_2025"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="description",
            field=models.CharField(default=None, max_length=15000, null=True),
        ),
    ]
