name: CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox_env: [python, flake8]
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bsync_validator
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Display system info
        run: python -c "import sys; print(sys.version)"
      - name: Setup Python
        run: |
          apt-get update && apt-get install python-enchant -y
          pip install tox
          pip install --upgrade pip
          pip install tox coveralls
      - name: Run tox
        env:
          DJANGO_SETTINGS_MODULE: bsyncviewer.settings.gh_actions
        run: tox -e ${{ matrix.tox_env }}
      - name: Coveralls
        if: ${{ success() && matrix.tox_env == 'python' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
